CREATE DATABASE BOOK_TRACKER

USE BOOK_TRACKER

CREATE TABLE BOOKS_STATUS (
	STATUS_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	STATUS_NAME VARCHAR(15)
);

CREATE TABLE USERS (
	USER_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
);

CREATE TABLE BOOKS (
	BOOK_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ADDED_BY_USER_ID INT NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	AUTHOR VARCHAR(50) NOT NULL,
	DATE_ADDED_TO_LIST DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
	NOTE INT,
	STATUS_ID INT NOT NULL

	FOREIGN KEY (ADDED_BY_USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (STATUS_ID) REFERENCES BOOKS_STATUS(STATUS_ID)
);
